### ISSUE TITLE
Can you please upload PCB assembly related files too?

### ISSUE THREAD

**Issue by halacs** [stephan192/hoermann_door#16]
Hi,

I would like to order this PCB from seedstudio.com in an assembled form. I need to upload assembly instructions and BOM files.

Can you please help me out with these?

I attach a screenshot about a web form I face with. Sorry for the dumb request. :)

Thanks!

![Screenshot 2023-01-20 at 21-13-53 Fusion PCB Manufacturing   Prototype PCB Assembly - Seeed Studio](https://user-images.githubusercontent.com/1415569/213797343-aedcdfab-2e7e-4ee7-8343-12c1b92fc3da.png)

**Comment by stephan192** [comment]
First of all: I assembled my board manually so the fabrication data is not 100% ready.

- I've added the pick&place file.
- The BOM is already in the repo ([partlist](https://github.com/stephan192/hoermann_door/blob/main/board/RS485Interface_partlist.txt)), but you must adjust it to seedstudio's requirements. Expecially the BOM doesn't contain "exact" part numbers. E.g. 10k 0805 is a generic 10k resistor in 0805 package which must be linked to an existing part. The pin headers (JP1, JP2, SV1, SV2, SV3) don't have values because i've just cut them of a longer pin header. When selecting expecially capacitors be careful with the rated voltage.
- I don't have any testplan, visual inspection is enough.
